name: Update Docker Image in Kubernetes Deployment

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      CLUSTER_NAME:
        required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Extract Repo Name
        id: vars
        run: echo "repo_name=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Deploy to Production
        run: |
          kubectl set image deployment/v010-${{ env.repo_name }} ${{ env.repo_name }}=ghcr.io/${{ github.repository }}:${{ inputs.tag }} -n docdirect-web-production
